### PR TITLE
Change Spark version from 2.0.2 to 2.2.0

### PR DESCRIPTION
**Pull request by yu-iskw**
We would like to change using spark version from 2.0.2 to 2.2.0. As well as, changing the Scala version from 2.10.6 to 2.11.8 would be good.

### CODE REVIEW

**Comment by yu-iskw** [comment]
@nevillelyh Thank you for merging it!

**Comment by nevillelyh** [comment]
Thanks for contributing! Are you building your own artifact or need it released in spark-packages? I had troubling releasing there in the past though :(

**Comment by yu-iskw** [comment]
Releasing the new version would help me and a bunch of people. What kind of trouble are you faced with to release it?

**Comment by nevillelyh** [comment]
I'll give it another shot.
The spark-packages.org backend isn't the most robust :)

**Comment by nevillelyh** [comment]
The artifacts are published to Sonatype.
spark-packages pending http://spark-packages.org/staging?id=2122

**Comment by yu-iskw** [comment]
We did it. The shot seems valid!!

**Pull request merged**
