### PR TITLE
Added support for Spark 2.4.0 and Scala 2.12. 

### PR DESCRIPTION
**Pull request by mrksmb**
Adjusted code slightly since Databricks Avro library moved into Spark with small syntax changes.

### CODE REVIEW

**Comment by nevillelyh** [comment]
Just realized that `spark-avro` is not available for Scala `2.12`. How did you get this to work in your build?
https://mvnrepository.com/artifact/com.databricks/spark-avro

**Comment by mrksmb** [comment]
It compiled fine, but I have yet to test the code change. Plan to do that today and will make adjustments if necessary.

**Comment by markus-braasch-ck** [comment]
Neville, I think Databricks donated the Avro library to Spark. Adding it as a dependency like this seems to work for me:
`libraryDependencies ++= Seq(
"org.apache.spark" %% "spark-avro" % sparkVersion
)`

https://mvnrepository.com/artifact/org.apache.spark/spark-avro

**Comment by ogirardot** [comment]
hi, thx for that, was the version published ?

**Comment by regadas** [comment]
It wasn't yet, I think we will do it next week.

**Pull request merged**
